### ISSUE TITLE
Not possible to use spline continuum fit

### ISSUE THREAD

**Issue by keheintz** [jkrogager/VoigtFit#23]
Hi JK,
Recently, I haven't been able to use the "norm_method: spline", but the linear function works as normal. Below is the error message I get when I try to add spline points to the continuum. Is it something to do with matplotlib? Thanks!

 Select a range of continuum spline points over the whole range
/Users/keheintz/VoigtFit/VoigtFit/regions.py:225: RuntimeWarning: divide by zero encountered in divide
  new_flux = self.flux/continuum
/Users/keheintz/VoigtFit/VoigtFit/regions.py:226: RuntimeWarning: divide by zero encountered in divide
  new_err = self.err/continuum
Traceback (most recent call last):
  File "//anaconda/envs/astroconda/bin/VoigtFit", line 11, in <module>
    sys.exit(main())
  File "/Users/keheintz/VoigtFit/VoigtFit/VoigtFit.py", line 491, in main
    dataset.prepare_dataset(mask=False, norm=norm, velocity=show_vel_norm)
  File "/Users/keheintz/VoigtFit/VoigtFit/dataset.py", line 1505, in prepare_dataset
    z_sys=z_sys)
  File "/Users/keheintz/VoigtFit/VoigtFit/regions.py", line 229, in normalize
    label=lines_title_string)
  File "//anaconda/envs/astroconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3363, in plot
    ret = ax.plot(*args, **kwargs)
  File "//anaconda/envs/astroconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "//anaconda/envs/astroconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1528, in plot
    for line in self._get_lines(*args, **kwargs):
  File "//anaconda/envs/astroconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 406, in _grab_next_args
    for seg in self._plot_args(this, kwargs):
  File "//anaconda/envs/astroconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 383, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "//anaconda/envs/astroconda/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 242, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (1,) and (244,)

**Comment by jkrogager** [comment]
This has been fixed in the latest version of the code.
