### ISSUE TITLE
Problems with Matplotlib

### ISSUE THREAD

**Issue by keheintz** [jkrogager/VoigtFit#57]
Hi! After updating a few packages + upgrading VoigtFit I get the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/voigtfit/bin/VoigtFit", line 5, in <module>
    from VoigtFit.main import main
  File "/opt/anaconda3/envs/voigtfit/lib/python3.9/site-packages/VoigtFit/main.py", line 18, in <module>
    warnings.filterwarnings("ignore", category=matplotlib.mplDeprecation)
  File "/opt/anaconda3/envs/voigtfit/lib/python3.9/site-packages/matplotlib/_api/__init__.py", line 226, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib' has no attribute 'mplDeprecation' 
Is this an issue with an older version of Matplotlib?

**Comment by jkrogager** [comment]
Hi. This should be fixed by commit 70b9b64. Version 3.16 should work... let me know otherwise.

**Comment by jkrogager** [comment]
Hey, I'm closing this as I assume that the given commit fixed the issue. Otherwise let me know and I'll reopen the issue. :)
